name: Test

on: push

jobs:
  test:
    name: TEST
    runs-on: ubuntu-latest
    env:
      TEST_REPORT: test-report

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Run test
        run: |
            go test -v -json ./... 2>&1 > >(tee ${{ env.TEST_REPORT }}.json)

      - name: Convert test result
        if: success() || failure()
        run: |
            go get -u   github.com/jstemmer/go-junit-report/v2
            go run      github.com/jstemmer/go-junit-report/v2 \
              -parser gojson \
              -in  ${{ env.TEST_REPORT }}.json \
              -out ${{ env.TEST_REPORT }}.xml \
              -set-exit-code

      - name: Test Summary
        if: success() || failure()
        uses: test-summary/action@v1
        with:
          paths: |
            ${{ env.TEST_REPORT }}.xml

      - name: Bump version and push tag on green tests in main
        # if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: anothrNick/github-tag-action@1.67.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          WITH_V: true
          DEFAULT_BUMP: none
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
